Update read me with new feature changes - generateConfluenceMarkdown
indeedeng/Mariner pull request #60
Opened 2021-02-23 01:10 UTC by IngridGdesigns

update the oss-mariner readme to reflect this new feature added

2021-02-24 18:03 UTC, kevindigo requested changes
The README changes mostly look great. I realized that we'll need to channel the function through mariner.ts. And I am a bit confused about the cleanup function.

2021-02-24 18:03 UTC, kevindigo commented on src/Utilities/generateConfluenceMarkdown.ts
> +    const cleanedMarkdown = removedParenthesis.replace(/\[?\]/, '').replace(/\[?\[/, ''); //Brute force to clean extra brackets
It looks like this is removing square brackets. And ... doing something else I don't understand. I'm curious why this extra code is needed, when Damon seemed to have one line that did what he felt was necessary. 

We should add tests to verify each specific thing that we believe clean needs to do.

2021-02-24 18:03 UTC, kevindigo commented on README.md
> +- The generateConfluenceMarkdown.ts file is inside the `src/Utilities` folder
We won't need to tell users this, because they will just be able to import the function via mariner.

2021-02-25 00:26 UTC, IngridGdesigns commented on src/Utilities/generateConfluenceMarkdown.ts
> +    const removedParenthesis = issueTitle.replace(/{|}/g, '');
It's not removing pipes, only curly braces, it was the code in Mariner-Issue-Collector and I checked in Regexr, the pipe "acts like a boolean OR. Matches the expression before or after the | " according to [Regexr](https://regexr.com/)

2021-03-02 00:36 UTC, kevindigo approved these changes
The tests look good. It just seems like they're more complicated than necessary.

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +import { generateConfluenceMarkdown, cleanMarkdown } from '../Utilities/generateConfluenceMarkdown';
This should probably import via mariner, like runFasterCode does.

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +            '|[2020 upgrade edition menus too narrow|https://github.com/marmelab/react-admin/issues/7520]|8&nbsp;days|'
This could expect toMatch(title1). That would make it clearer that no changes are expected.

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +            '|[2020 upgrade edition menus too narrow|https://github.com/marmelab/react-admin/issues/7520]|8&nbsp;days|'
Why is this toMatch and not toEqual?

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +        const url = 'https://github.com/marmelab/react-admin/issues/3450]';
I don't think we need any variables other than title here. The function just takes a title and returns a cleaned-up title. The test makes it look like more is going on.

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +        expect(cleanedMarkdown).toContain(`|[WIP updating frontend components|${url}|${days}|`);
Rather than a .not.toContain and a .toContain, I think a single .toEqual should be enough.

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +        const url = 'https://github.com/babel/babel/issues/1254]';
Same comment as above. I think this can just have title, and a single .toEqual.

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +        const url = 'https://github.com/es-lint/es-lint/issues/2345]';
Same comment as above (title, .toEqual).

2021-03-02 00:36 UTC, kevindigo commented on src/__tests__/generateConfluenceMarkdown.test.ts
> +    it('should not remove brackets', () => {
I would say square brackets in the test description, to make it super clear.

2021-03-02 01:14 UTC, kevindigo requested changes
Just one more change (my fault).

2021-03-02 01:14 UTC, kevindigo commented on src/mariner/index.ts
> +export { generateConfluenceMarkdown, cleanMarkdown } from '../Utilities/generateConfluenceMarkdown';
Oh crap. We don't want mariner to export that. Sorry!

The test should import generateConfluenceMarkdown from mariner, but should import cleanMarkdown directly from the source file as you had it.

2021-03-02 01:41 UTC, kevindigo approved these changes

2021-03-02 01:42 UTC, merged